version: '3'
services:
  sonarr:
    image: "linuxserver/sonarr"
    ports:
      - "10.8.0.1:8989:8989"
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: "Europe/Madrid"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ../kodi/media/series:/tv
      - ../transmission/downloads/complete:/downloads
