version: '3'
services:
  kodi:
    image: "linuxserver/kodi-headless"
    ports:
      - "10.8.0.1:8080:8080"
      - "10.8.0.1:9777:9777/udp"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "Europe/Madrid"
    volumes:
      - ./config/.kodi:/config/.kodi
      - ./media:/media
