version: "3"

services:
  tor-es:
    image: dperson/torproxy
    container_name: tor-es
    ports:
      - 8118:8118
      - 9050:9050
    environment:
      LOCATION: ES
    restart: unless-stopped

  tor-us:
    image: dperson/torproxy
    container_name: tor-us
    ports:
      - 8119:8118
      - 9051:9050
    environment:
      LOCATION: US
    restart: unless-stopped
