version: '3'
services:
  transmission:
    image: "linuxserver/transmission"
    ports:
      - "10.8.0.1:9091:9091"
      - "51213:51213"
      - "51213:51213/udp"
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: "Europe/Madrid"
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./watch:/watch
